#!/usr/bin/env node
/**
 * Build script to generate tokens.css from tokens.json
 *
 * Usage: node tokens/build-tokens.js
 *
 * This creates a single source of truth:
 * 1. Edit tokens/tokens.json
 * 2. Run this script
 * 3. tokens.css is updated with new values
 */

const fs = require('fs');
const path = require('path');

const tokensPath = path.join(__dirname, 'tokens.json');
const outputPath = path.join(__dirname, '..', 'styles', 'tokens.css');

function flattenTokens(obj, prefix = '') {
  const result = [];

  for (const [key, value] of Object.entries(obj)) {
    const varName = prefix ? `${prefix}-${key}` : key;

    if (value && typeof value === 'object' && 'value' in value) {
      // This is a token with a value
      result.push({
        name: `--${varName}`,
        value: value.value,
        description: value.description || null
      });
    } else if (value && typeof value === 'object') {
      // This is a nested group, recurse
      result.push(...flattenTokens(value, varName));
    }
  }

  return result;
}

function generateCSS(tokens) {
  const grouped = {};

  // Group by top-level category
  tokens.forEach(token => {
    const category = token.name.split('-')[1]; // e.g., "color" from "--color-primary"
    if (!grouped[category]) grouped[category] = [];
    grouped[category].push(token);
  });

  let css = `/*
 * DESIGN TOKENS
 * =============
 * Auto-generated from tokens/tokens.json
 * Run: node tokens/build-tokens.js
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit tokens/tokens.json instead
 */

:root {
`;

  for (const [category, categoryTokens] of Object.entries(grouped)) {
    css += `\n  /* ${category.toUpperCase()} */\n`;
    categoryTokens.forEach(token => {
      if (token.description) {
        css += `  /* ${token.description} */\n`;
      }
      css += `  ${token.name}: ${token.value};\n`;
    });
  }

  css += `}\n`;

  return css;
}

// Main
try {
  const tokensJson = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));
  const flatTokens = flattenTokens(tokensJson);
  const css = generateCSS(flatTokens);

  fs.writeFileSync(outputPath, css);
  console.log(`✅ Generated ${outputPath}`);
  console.log(`   ${flatTokens.length} tokens exported`);
} catch (error) {
  console.error('❌ Error:', error.message);
  process.exit(1);
}
